#!/bin/sh
# Skip if called from within pre-push (to avoid double-bump)
[ "$SKIP_VERSION_BUMP" = "1" ] && exit 0

node -e "
const fs = require('fs');
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
const [major, minor, patch] = pkg.version.split('.').map(Number);
pkg.version = \`\${major}.\${minor}.\${patch + 1}\`;
fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
console.log('Version bumped to', pkg.version);
"
git add package.json
